# Generated by Django 3.1 on 2020-08-19 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('workid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, default='Warner', max_length=255, null=True)),
                ('timezn', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
